tests:async: Fix Python3.12 deprecation warning
Using the old signature to `throw()`, Python3.12 will complain with the following DeprecationWarning:

FAILED tests/test_async_py3.py::test_func_10[normal-cext] - DeprecationWarning: the (type, exc, tb) signature of throw() is deprecated, use the single-arg signature instead.

See: https://docs.python.org/3/reference/expressions.html#generator.throw